[package]
name = "thing"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
#bootloader = { version = "0.11.0", features = [ "uefi" ] }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


